SELECT* FROM LMS_BOOK_DETAILS;
SELECT* FROM LMS_BOOK_ISSUE;
SELECT* FROM LMS_FINE_DETAILS;
SELECT* FROM LMS_MEMBERS;
SELECT* FROM LMS_SUPPLIERS_DETAILS;

--1
SELECT* FROM LMS_SUPPLIERS_DETAILS;
SELECT* FROM LMS_BOOK_DETAILS;

SELECT BOOK_TITLE,SUPPLIER_NAME FROM LMS_BOOK_DETAILS AS L1 JOIN LMS_SUPPLIERS_DETAILS AS L2 ON L1.SUPPLIER_ID=L2.SUPPLIER_ID;

--2

SELECT* FROM LMS_BOOK_ISSUE;
SELECT* FROM LMS_BOOK_DETAILS;

SELECT MEMBER_NAME,BOOK_CODE FROM LMS_MEMBERS AS L1 JOIN LMS_BOOK_ISSUE AS L2 ON L1.MEMBER_ID=L2.MEMBER_ID ;

--3

SELECT* FROM LMS_BOOK_DETAILS;
SELECT* FROM LMS_BOOK_ISSUE;



SELECT BOOK_TITLE,DATE_ISSUE FROM LMS_BOOK_DETAILS AS L1 JOIN LMS_BOOK_ISSUE AS L2 ON L1.BOOK_CODE=L2.BOOK_CODE;

--4

SELECT* FROM LMS_FINE_DETAILS;
SELECT* FROM LMS_BOOK_ISSUE;

SELECT MEMBER_ID,FINE_AMOUNT FROM LMS_FINE_DETAILS AS L1 JOIN LMS_BOOK_ISSUE AS L2 ON L1.FINE_RANGE=L2.FINE_RANGE;

--5

SELECT* FROM LMS_BOOK_ISSUE;
SELECT* FROM LMS_MEMBERS;

SELECT MEMBER_NAME,DATEDIFF(YEAR,DATE_RETURN,DATE_RETURNED) AS DATE_DIFF FROM LMS_MEMBERS AS L1 JOIN LMS_BOOK_ISSUE AS L2 ON L1.MEMBER_ID=L2.MEMBER_ID;

--6
SELECT* FROM LMS_BOOK_DETAILS;
SELECT* FROM LMS_MEMBERS;
SELECT* FROM LMS_BOOK_ISSUE;

SELECT BOOK_TITLE,MEMBER_NAME FROM LMS_MEMBERS AS L1 JOIN LMS_BOOK_ISSUE AS L2 ON L1.MEMBER_ID=L2.MEMBER_ID JOIN  LMS_BOOK_DETAILS AS L3 ON L3.BOOK_CODE=L2.BOOK_CODE; 

--7
SELECT* FROM LMS_MEMBERS;
SELECT* FROM LMS_BOOK_ISSUE;
SELECT* FROM LMS_BOOK_DETAILS;

SELECT* FROM LMS_SUPPLIERS_DETAILS;
SELECT BOOK_TITLE,MEMBER_NAME,SUPPLIER_NAME FROM LMS_BOOK_DETAILS AS L1 JOIN   LMS_SUPPLIERS_DETAILS AS L2 ON L1.SUPPLIER_ID= L2.SUPPLIER_ID JOIN LMS_MEMBERS AS L3 ON L3.CITY=L2.ADDRESS;

--8

SELECT* FROM LMS_BOOK_DETAILS;
SELECT* FROM LMS_FINE_DETAILS;
